config/routes.rb
Rails.application.routes.draw do
	root 'static#home'

	get '/about' => 'static#about'
	get '/services' => 'static#services'

	match '/contact', to: 'contacts#new', via: 'get'
	resources 'contacts', only: [:new, :create]

	match '/join_us', to: 'tutors#new', via: 'get'
	resources 'tutors', only: [:create]
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :number,    :validate => /\d{3}-\d{3}-\d{4}/
	attribute :file, 			:attachment => true
	attribute :availability, validate: true
  attribute :message
  attribute :nickname,  :captcha  => true

	# Declare the e-mail headers. It accepts anything the mail method
	# in ActionMailer accepts.

	def headers
    {
      :subject => "Easy As Pi Contact",
      :to => "learningeasyaspi@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/tutor.rb
class Tutor < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :number,    :validate => /\d{3}-\d{3}-\d{4}/
	attribute :file, 			:attachment => true
	attribute :subjects,  :validate => true
	attribute :education, :validate => true
	attribute :availability, :validate => true
  attribute :message
	validates_length_of :message, minimum: 100
	attribute :terms
	validates_acceptance_of :terms, acceptance: true 
  attribute :nickname,  :captcha  => true

	# Declare the e-mail headers. It accepts anything the mail method
	# in ActionMailer accepts.

	def headers
    {
      :subject => "Easy As Pi Tutor Application",
      :to => "learningeasyaspi@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController 
	
	def new
		@contact = Contact.new 
	end

	def create 
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver 
			flash[:success] = 'Thank you for your message. We will get back to you soon!'
			redirect_to contact_url
		else 
			flash.now[:danger] = 'Error sending message 😔. Please try again.'
			render :new
		end
	end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def home
	end

	def about
	end
	
	def services
	end

	def tutors
	end

	def contact
	end

end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController 

	def new
		@tutor = Tutor.new
	end

	def create 
		@tutor = Tutor.new(params[:tutor])
		@tutor.request = request
		if @tutor.deliver 
			flash[:success] = 'Thank you for applying. We will get back to you soon! 😀 '
			redirect_to join_us_url
		else 
			flash.now[:danger] = 'Error sending application. Please try again.'
			render :new
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% content_for :title do %>Contact Us<% end %>

<div class="full-bg contact-pg">
	<div class="container">
	 <%= flash_messages %>
	
	<div align="center" class="col-md-7 col-md-offset-2">
		<h1>Contact Form</h1>

		<%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
			<%= f.input :name, required: true %>
			<%= f.input :email, required: true %>
			<%= f.input :number, required: true, placeholder: 'XXX-XXX-XXXX', label: 'Number (ex. 416-967-1111)' %>
			<h4>Availability <small>(Select all that apply)</small></h4>
			<%= f.collection_check_boxes :availability, [['Monday', 'Monday'] ,['Tuesday', 'Tuesday'],['Wednesday', 'Wednesday'],['Thursday', 'Thursday'],['Friday', 'Friday'],['Saturday', 'Saturday'], ['Sunday', 'Sunday']], :first, :last %>
			<%= f.input :message, :as => :text, label: 'Comments/Concerns'%>
			<div class= "hidden">
				<%= f.input :nickname, :hint => 'Leave this field blank!' %>
			</div>
			<div>
				</br>
				<%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
			</div>
		<% end %>
	</div>
<div class="flex-map col-md-10 col-md-offset-1">
		<div id="map"></div>
		<div id="address">
		<h3>3773 Ellesmere Road <br/> Toronto, Ontario</h3>
		<h4><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (647)-909-9314</h3>
		</div>
	</div>
	</div>
</div>

<script>


function initMap() {
  var myLatLng = {lat: 43.7915315, lng: -79.1674948};

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Easy As Pi Tutors'
  });
}


</script>

<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>

app/views/layouts/_footer.html.erb
<footer>

	<div class="copyright">
    <p>&copy 2015 - EasyAsPi</p>
  </div>
  <div class="social">
    <a href="#" class="face" id="fb">f</a>
    <a href="#" class="tweet" id="tweet">t</a>
    <a href="#" class="linked" id="linked">in</a>
	  <a href="#" class="g-logo" id="g-plus">g+</a>
  </div>
	
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/"><img id="eap-logo" src="assets/new-logo.svg" alt="Logo"/></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'About', about_path %></li>
				<li><%= link_to 'Services', services_path %></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tutors <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><%= link_to 'Join Us', join_us_path %></li>
					</ul>
				</li>
        <li><%= link_to 'Contact Us', contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title><%= content_for?(:title) ? "Easy As Pi - "+ yield(:title) : "Easy As Pi" %></title>
			<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Easy As Pi Tutoring" %>">
			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<%= favicon_link_tag 'favicon.ico' %>
			<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	</head>
	<body>

		<%= render 'layouts/nav' %>

		<%= yield %>


		<%= render 'layouts/footer' %>

	</body>
</html>

app/views/tutors/new.html.erb
<div class="full-bg tutors-pg">

<div class="container">
 <%= flash_messages %>

<div align="center" class="col-md-7 col-md-offset-2">
  <h1>Interested in joining our team?</h1>

  <%= simple_form_for @tutor, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, required: true %>
    <%= f.input :email, required: true %>
		<%= f.input :number, required: true, placeholder: 'XXX-XXX-XXXX', label: 'Number (ex. 416-967-1111)' %>
		<h4>Choose highest level completed</h4>
		<%= f.collection_radio_buttons :education, [['High-School', 'High-School'] ,['Post-Secondary', 'Post-Secondary'],['Post-Grad', 'Post-Grad'], ['OCT', 'OCT']], :first, :last %>
		<h4>Availability <small>(Select all that apply)</small></h4>
		<%= f.collection_check_boxes :availability, [['Monday', 'Monday'] ,['Tuesday', 'Tuesday'],['Wednesday', 'Wednesday'],['Thursday', 'Thursday'],['Friday', 'Friday'], ['Saturday', 'Saturday'], ['Sunday', 'Sunday']], :first, :last %>
		<h4>Teachable Subjects <small>(Check all that apply)</small></h4>
		<%= f.collection_check_boxes :subjects, [['Math', 'Math'] ,['Biology', 'Biology'],['Chemistry', 'Chemistry'],['Physics', 'Physics'],['Other', 'Other']], :first, :last %>
		</br>
		<h4>Attach Resume <small>in .doc, or .pdf format</small></h4>
		<%= f.file_field :file %></br>
    <%= f.input :message, :as => :text, label: 'Tell us about yourself, and why you would like to tutor for us'%>
		<h5>All tutors are required to pass a criminal background check, by checking the box below you acknowledge this statement</h5>
		<%= f.check_box :terms, value: 'true', class: 'terms-box' %>
		<%= f.label :terms,'I Agree', class: 'terms-label' %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

</div>

</div>